#!/bin/sh

if [ "$1" != "" ]; then
	PORT=$1
else
	PORT=8000
fi

# Linux ifconfig interesting lines are like: inet addr:192.168.0.5  Bcast:192.168.0.255  Mask:255.255.255.0
# MacOS ifconfig interesting lines are like: inet 192.168.0.5 netmask 0xffffff00 broadcast 192.168.0.255
# This awk script will split the second argument (either 'addr:ip' or just 'ip') and retrieve the 'ip' whatever the case.
if [ -x /bin/ip ]; then
	/bin/ip a | grep -w inet | sed -e 's_/.*__g' | awk -v PORT=$PORT '{ print "http://" $2 ":" PORT }'
elif [ -x /sbin/ifconfig ]; then
	/sbin/ifconfig | grep -w inet | awk -v PORT=$PORT '{ split($2, ip, ":"); if (ip[2] == "") useIp = $2; else useIp = ip[2]; print "http://" useIp ":" PORT }'
fi

python3 -m http.server $PORT

